config/routes.rb
Smartset::Application.routes.draw do
	
	resources :countries
	resources :currencies
	resources :trips
	
	match "currency_countries", :to => "currencies#currency_countries", :as =>"currency_countries"
	match "country_currencies", :to => "countries#country_currencies", :as =>"country_currencies"
	
	match "/trips/destroy/:id", :to => "trips#destroy", :as =>"destroy_trip"
		
	# map.update_service "/update/service/:name", :controller=>"woodpecker", :action=>"update_service"
	match "update_country/:id", :to => "countries#update_country", :as =>"update_country"
	match "update_toggle", :to => "currencies#update_toggle", :as =>"update_toggle"
	
	match "update_trip_status/:id", :to => "trips#update_status", :as =>"update_trip_status"

	match '/logout', :to=> "sessions#destroy", :as=> "logout"
	match '/login', :to=> "sessions#new", :as=> "login"
	resources :users
  	resource :session
  	
	root :to => 'home#index'
end

app/models/trip.rb
class Trip < ActiveRecord::Base

has_and_belongs_to_many :countries

before_save :update_visited_countries

	def initialize(keys={})
		super
		self.date ||= Time.now
		self.status ||= 'incompleted'
	end
	
	def update_visited_countries
		if self.status == 'completed'
		self.countries.each{|country|
			country.visited = true
			country.save
			#country.currencies.each{|currency|
			#	currency.collected = true
			#	currency.save	
			#}	
		}
		end
	end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
	before_filter :login_required, :except => [:index, :show]
	
	def index
		@trips = Trip.find(:all, :order => "created_at ASC")
		@visited_countries_size = Country.visited?(true).count
	end
	
	def show
		@trip = Trip.find(params[:id])
		respond_to do |format|
			format.html # show.html.erb
			format.xml  { render :xml => @trip }
		end
	end
  
	def new
		@trip = Trip.new
		@countries = Country.order("name").select{|country| country.visited == false}
		respond_to do |format|
			format.html # new.html.erb
			format.xml  { render :xml => @trip }
		end
	end
	
	def edit
		@trip= Trip.find(params[:id])
		@countries = Country.order("name").select{|country| country.visited == false}
	end

	def create
		@trip = Trip.new(params[:trip])
		unless params[:country_id].nil?
			params[:country_id].each{|country_id|
				@trip.countries.push(Country.find(country_id))
			}
		end
		respond_to do |format|
			if @trip.save
        		flash[:notice] = "Trip was successfully created."
        		format.html { redirect_to(@trip) }
        		format.xml  { render :xml => @trip, :status => :created, :location => @tripe }
			else
				format.html { render :action => "new" }
				format.xml  { render :xml => @trip.errors, :status => :unprocessable_entity }
			end
		end
	end
	
	def update
		@trip = Trip.find(params[:id])
		respond_to do |format|
			if @trip .update_attributes(params[:trip ])
				flash[:notice] = 'Trip  was successfully updated.'
				format.html { redirect_to(@trip ) }
				format.xml  { head :ok }
			else
				format.html { render :action => "edit" }
				format.xml  { render :xml => @trip .errors, :status => :unprocessable_entity }
			end
		end
	end

	def destroy
		@trip = Trip.find(params[:id])
		@trip.destroy #if current_user.id == @trip.user_id
		respond_to do |format|
			format.html { redirect_to(trips_url) }
			format.xml  { head :ok }
		end
	end
	
	def update_status	#params[:id]
			trip = Trip.find(params[:id])
			if trip['status']=='incompleted'
				trip['status']='completed'
				trip.save
			end
			
		redirect_to :back, :params => @params
	end
end

app/views/trips/_form.html.erb
<%= javascript_include_tag :defaults %>

<% form_for(@trip) do |trip_form| %>
<%= errors_for(@trip, "Unable to add new trip").html_safe %>

<div class="trip_form">
<% unless @trip.nil? %>
 <% form_for(@trip) do |trip_form| %>
<table id="table"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td width="20%">Trip description</td>
<td width="50%"><%= trip_form.text_area :description, :rows => 10, :cols => 40 %></td>
<td>
<% @trip.errors['description'].each do |error| %>
<%=error%><br />
<% end %>&nbsp;
</td>
</tr>
<tr>
<td>Trip date</td><td><%= trip_form.text_field :date, :size=>50 %> <br /></td>
<td>
<% @trip.errors['date'].each do |error| %>
<%=error%><br />
<% end %>&nbsp;
</td>
</tr>
<tr>
<td>Trip Status</td><td><%#= trip_form.text_field :status, :disabled=>true  %><%= trip_form.select(:status, ['incompleted','completed'], {})%></td>
<td>
<% @trip.errors['status'].each do |error| %>
<%=error%><br />
<% end %>&nbsp;
</td>
</tr>
<tr><th colspan="3">Countries</td></tr>
<tr>
<% @countries.each do |country|%>
<td><label id="<%=country.id%>" name="<%=country.name%>"><%= check_box_tag("country_id[]", country.id, false) %></label></td>
<td colspan="2"><font size="1"><%= label_tag country.id, country.name%> 
</font></td></tr>
 <% end %>
</table>
 <% end %>
<% end %>
</div>
<p><center><%= trip_form.submit "Save" %></center></p>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render :partial => "form" %>
<center>
<%= link_to 'Trips', trips_path %> |
<%= link_to 'Show', @trip %> |
<%= link_to 'Destroy', @trip, :confirm => 'Are you sure?', :method => :delete, :remote=>true %>
</center>

app/views/trips/index.html.erb
<table id="all_visited_countries"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<th align="center">Number of visited countries: <b><%= @visited_countries_size%></b></td>
</tr>
<tr>
<td align="center"><%= button_to 'Add new trip', new_trip_path, :method => 'get' %></td>
</tr>
</table>

<table id="form_trips"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<th width="40%" align="center">Trip description</td>
<th align="center"  width="20%" >Trip date</td>
<th align="center"> Visited countries</td>
<th align="center"> Trip status</td>
</tr>
<% @trips.each_with_index do |trip, index| %>
<tr>
<td><%= trip.description %> <%= link_to '>', trip %></td>
<td><%= trip.date %></td>
<td>
<% trip.countries.each_with_index  do |country, index| %>
<%= link_to country.name, country_currencies_path(:id=>country.id) %> 
<% if country.visited %>
		<%= image_tag("icons/status_checked.png",:border=>0, :title=>'visited') %>
	<% else %>
		<%= image_tag("icons/status_shutdown.png",:border=>0, :title=>'not_visited') %>
	<% end %><br />

<% end %>
</td>
<td><%= trip.status %> 
<% if trip.status=='incompleted' %>
	<%=link_to image_tag("icons/button_orange.png",:border=>0, :title=>'to_complete', :id => "to_complete"), update_trip_status_path(:id=>trip.id)%>
<% else %>
	<%= image_tag("icons/status_checked.png",:border=>0, :title=>'completed') %>
<% end %>
</td>
</tr>
<% end %>
</table>

app/views/trips/new.html.erb
<h1>New Trip</h1>
<%#= debug params %>
<%= render :partial => "form" %>

<center><%= button_to 'Back', trips_path, :method=>'get'%></center>

app/views/trips/show.html.erb
<h1>Show Trip</h1>
<table id="table"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<td width="20%">Trip description</td><td><%= raw @trip.description.gsub(/\n/, '<br/>').gsub(/\<script/, '') %>&nbsp;</td>
</tr><tr>
<td>Date</td><td><%= @trip.date%>&nbsp;</td>
</tr><tr>
<td>Status</td><td><%= @trip.status %>&nbsp;</td>
</tr><tr>
<td>Countries</td><td>
<% @trip.countries.each_with_index  do |country, index| %>
<%= country.name %>
<% if country.visited %>
		<%= image_tag("icons/status_checked.png",:border=>0, :title=>'visited') %>
	<% else %>
		<%= image_tag("icons/status_shutdown.png",:border=>0, :title=>'not_visited') %>
	<% end %>

<br />
<% end %>
</td>
</tr>

</table>

<center>

<%= link_to 'Trips', trips_path %> |
<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%#= link_to 'Destroy', @trip, :confirm => 'Are you sure?', :method => :delete, :remote=>true %>
<%= link_to 'Destroy', destroy_trip_path(:id=>@trip.id)%>
</center>