config/routes.rb
Smartset::Application.routes.draw do
	
	resources :countries
	resources :currencies
	resources :trips
	
	match "currency_countries", :to => "currencies#currency_countries", :as =>"currency_countries"
	match "country_currencies", :to => "countries#country_currencies", :as =>"country_currencies"
	
	match "/trips/destroy/:id", :to => "trips#destroy", :as =>"destroy_trip"
		
	# map.update_service "/update/service/:name", :controller=>"woodpecker", :action=>"update_service"
	match "update_country/:id", :to => "countries#update_country", :as =>"update_country"
	match "update_toggle", :to => "currencies#update_toggle", :as =>"update_toggle"
	
	match "update_trip_status/:id", :to => "trips#update_status", :as =>"update_trip_status"

	match '/logout', :to=> "sessions#destroy", :as=> "logout"
	match '/login', :to=> "sessions#new", :as=> "login"
	resources :users
  	resource :session
  	
	root :to => 'home#index'
end

app/models/currency.rb
class Currency < ActiveRecord::Base

#has_and_belongs_to_many :countries
  has_many :monetizations, :dependent => :destroy
  has_many :countries, :through => :monetizations

	def initialize(keys={})
		super
		self.collected ||= false
	end
	
	def self.by_name(name)
		#find(:all, :conditions => ["name = ?", name.to_s])
		where(:name => name.to_s)
	end
	
	def self.by_currencycode(code)
		#find(:all, :conditions => ["name = ?", name.to_s])
		where(:currencycode => code.to_s)
	end
	
	def self.by_visited(v)
		self.all.select {|currency| currency.monetizations[0].visited == v}
	end
	
	def self.by_visited_and_name(v, name)
		self.where(:name => name).select {|currency| currency.monetizations[0].visited == v}
	end

	def self.collected?(v)
		where(:collected => v)
	end
	
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController

	def index
			if params[:view_visited]
				@currencies = Currency.by_visited(false)
			else
				@currencies = Currency.order("name")
			end
			@countries_by_currencyname = {}
			@not_visited_countries_by_currencyname = {}
			@countries_by_currencycode = {}
			@not_visited_countries_by_currencycode = {}
			
			@currencies.each{|currency|
				@not_visited_countries_by_currencyname["#{currency.name}"] = Currency.by_visited_and_name(false,currency.name).size
				@countries_by_currencyname["#{currency.name}"] = Currency.by_name(currency.name).size
#				@countries_by_currencyname["#{currency.name}"] ||=0
#				@not_visited_countries_by_currencyname["#{currency.name}"] ||=0
				@countries_by_currencycode["#{currency.currencycode}"] ||=0
				@not_visited_countries_by_currencycode["#{currency.currencycode}"] ||=0
			
				currency.countries.each{|country|
					@countries_by_currencycode["#{currency.currencycode}"] +=1
					@not_visited_countries_by_currencycode["#{currency.currencycode}"] +=1 if country['visited']==false
#					@countries_by_currencyname["#{currency.name}"] +=1
#					@not_visited_countries_by_currencyname["#{currency.name}"] +=1 if country['visited']==false
				}
			}
	end
	
	def currency_countries
		unless params[:currencycode].nil?
			@currencies = Currency.by_currencycode(params[:currencycode])
		else
			@currencies = Currency.by_name(params[:name])
		end
			@currency_countries = []
			@currencies.each{|currency|
			@currency_countries += currency.countries
			}
			@currency_countries.sort! {|c1,c2| c1.name.downcase <=> c2.name.downcase}
	end
	
end

app/helpers/currencies_helper.rb
module CurrenciesHelper

	def toggle_value(id)
		Country.update_country(id)
	end
end

app/views/currencies/_check_country.html.erb
<%= country.visited %>

<%= form_for country, :remote => true, :url => update_country_path(country.id) do |f| %>
<label id="<%=country.id%>" name="<%=country.name%>"><%= f.check_box 'visited', :class => 'submittable'  %></label>
<%#= check_box_tag country.name, country.id, country.visited, :id=>"c_#{country.id}" %>

<% end %>

app/views/currencies/currency_countries.html.erb
<table id="form_countries"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">

<tr>
<th  width="20%" align="center">Currency ISO</td>
<th align="center">Currency name</td>
<th  width="20%" align="center"></td>
</tr>
<tr>
<td><%= params[:currencycode] %></td><td><%= params[:name] %></td>
<td></td>
</tr>

<tr>
<th width="20%" align="center">Country code</td>
<th align="center">Country name</td>
<th align="center">Visited?</td>
</tr>
<% @currency_countries.each_with_index do |country, index| %>
<tr>
<td><%= country.countrycode %></td><td><%= link_to country.name, country_currencies_path(:id=>country.id) %></td>
<td>
<div id="c_<%=country.id%>">
<%=render :partial=>"currencies/check_country", :locals => { :country => country }%>
</div>


</td>
</tr>
<% end %>
</table>

app/views/currencies/index.html.erb
<table id="form_currencies"  width="80%" align="center" style="background-color:silver" cellpadding="2" cellspacing="0" border="1">
<tr>
<th width="20%" align="center">ISO</td>
<th align="center">Currency name (not visited / all countries)
<font size="1"><%= @toggle %>
<%= link_to 'View not visited', currencies_path(:view_visited=>true), :method => 'get' %></font>
</td>
<th width="20%" align="center">Collected?</td>
</tr>
<% @currencies.each_with_index do |currency, index| %>
<% next if currency.name.empty? %>
<tr>
<td><%= link_to currency.currencycode, currency_countries_path(:currencycode=>currency.currencycode) %>
(<%= @not_visited_countries_by_currencycode["#{currency.currencycode}"] %>/<%= @countries_by_currencycode["#{currency.currencycode}"] %>)

 </td><td><%= link_to currency.name, currency_countries_path(:name=>currency.name) %>
 (<%= @not_visited_countries_by_currencyname["#{currency.name}"] %>/<%= @countries_by_currencyname["#{currency.name}"] %>)
 
 </td>
 <td><% if currency.collected %>
		<%= image_tag("icons/status_checked.png",:border=>0, :title=>'visited') %>
	<% else %>
		<%= image_tag("icons/status_shutdown.png",:border=>0, :title=>'not_visited') %>
	<% end %>
 </td>
</tr>
<% end %>
</table>